import numpy as np

DATASET_CONFIGS = {
    "moving_mnist": {
        "kind": "moving_mnist",
        "path": "datasets/2D/mnist_test_seq.npy",
        "train_slice": slice(0, 2000),
        "test_slice": slice(9500, 9700),
        "image_size": (64, 64),
        "learning_rate": 3e-4,
        "LATENT_DIM": 128,
        "HIDDEN_DIM": 128,
        "EPOCHS": 10,
        "BETTI_SCALE": 15,
        "N_STEPS": 25,
        # params for TDA-on-latents: 
        "LATENT_TDA_WINDOW" : 20,
        "LATENT_TDA_BINS"   : 16,
        "LATENT_TDA_EPOCHS" : 10,
    },
    "davis_images": {
        "kind": "davis_images",
        "root": "datasets/2D/davis_images",
        "seq_len": 20,
        "stride": 5,
        "train_ratio": 0.7,
        "seed": 42,
        "max_train_windows": 400,
        "max_test_windows": 100,
        "image_size": (64, 64),
        "learning_rate": 1e-4,
        "LATENT_DIM": 16,
        "HIDDEN_DIM": 128,
        "EPOCHS": 10,
        "BETTI_SCALE": 1,
        "N_STEPS": 25,
        # params for TDA-on-latents: 
        "LATENT_TDA_WINDOW" : 20,
        "LATENT_TDA_BINS"   : 16,
        "LATENT_TDA_EPOCHS" : 10,
    },
    "celltracking_fluo": {
        "kind": "tif_folder",
        "folder": "datasets/2D/celltracking_fluo/01",
        "train_slice": slice(0, 45),
        "test_slice": slice(45, None),
        "image_size": (64, 64),
        "learning_rate": 3e-4,
        "LATENT_DIM": 128,
        "HIDDEN_DIM": 128,
        "EPOCHS": 10,
        "BETTI_SCALE": 15,
        "N_STEPS": 25,
        # params for TDA-on-latents: 
        "LATENT_TDA_WINDOW" : 20,
        "LATENT_TDA_BINS"   : 16,
        "LATENT_TDA_EPOCHS" : 10,
    },
    "glioblastoma": {
        "kind": "tif_folder",
        "folder": "datasets/2D/glioblastoma/01",
        "train_slice": slice(0, 45),
        "test_slice": slice(45, None),
        "image_size": (64, 64),
        "learning_rate": 3e-4,
        "LATENT_DIM": 128,
        "HIDDEN_DIM": 128,
        "EPOCHS": 10,
        "BETTI_SCALE": 15,
        "N_STEPS": 25,
        # params for TDA-on-latents: 
        "LATENT_TDA_WINDOW" : 20,
        "LATENT_TDA_BINS"   : 16,
        "LATENT_TDA_EPOCHS" : 10,
    },}
